### ISSUE TITLE
Get DOI for fbpic github repo

### ISSUE THREAD

**Issue by soerenjalas** [fbpic/fbpic#10]
For giving this repository more visibility it would be nice to be able to cite it in publication. To do this in a somewhat standardised form a DOI would be good to have.

This [guide](https://guides.github.com/activities/citable-code/) describes the necessary steps to get a DOI via a service called Zenodo.
As I understand this Zenodo takes the releases from the repository, archives them and links them with a DOI. The DOI link then points to a page in Zenodo, where citations can be generated in the standard formats, e.g. bibtex.
One downside I see in this is that the DOI links to the Zenodo page, which only then, indirectly, links to github.

Here, as an example is the DOI of the openPMD standard
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.33624.svg)](https://doi.org/10.5281/zenodo.33624)

Another option would be to create a custom bibtex snipped, which we are happy with, and then but it somewhere in this repo, e.g. the README. That way citation would also be somewhat consistent.

**Comment by RemiLehe** [comment]
It seems that the zenodo way is the more standard way of doing this. While I am not a fan of the fact that they do not link directly to the Github page, as you mentioned, I can still see two advantages in using Zenodo:
- Since it is more standard, it means journals are more likely to accept the bibtex entry for the code. (Some journals tend to be very picky on Bibtex entries, and if we cook up our own Bibtex entry, they might not accept it.)
- When we do new releases, the zenodo citation gets automatically updated (at least this is what I understood). On the other hand, if we do our own Bibtex citation, we will have to update it by hand everytime.

So for the moment, I slightly prefer the Zenodo way, even if it is not ideal. But if the other FBPIC contributors are strongly against it, I am open to the other option.

Also, I put the "help wanted" flag, meaning I personally won't have the time to do a corresponding PR for this issue, but anyone else can take the lead on this issue and do a PR.

**Comment by MKirchen** [comment]
Im in favor of zenodo.

**Comment by MKirchen** [comment]
The zenodo referencing is setup and should become active with the next release.

**Comment by RemiLehe** [comment]
Thanks!
