### ISSUE TITLE
Make field push more readable: keep the standard PSATD routines

### ISSUE THREAD

**Issue by RemiLehe** [fbpic/fbpic#12]
In pull request #6, the field push routine for the standard PSATD is replaced by the field push routine for the Galilean/comoving scheme. 

However, I think this makes it less readable for people who are just interested in the standard PSTAD scheme. Although the Galilean/comoving coefficients reduce to the standard PSATD when `ps.V` is 0, it is not obvious at a first glance.  I think keeping a separate, simpler function for the standard PSATD would be easier.

@MKirchen : Any opinion on this?

**Comment by MKirchen** [comment]
Okay with this. I also agree that the Galilean coefficients make it hard to understand the basic PSATD field push function when reading the code. However, I am wondering if you then always want to use the "standard PSATD" implementation if V=0?

(Because setting V=0 in the Galilean-PSATD equations was always a good test to search for bugs in the Galilean implementation)

Maybe we can set v_galilean to "None" by default. If so, the code will use the standard PSATD implementation. If however, v_galilean is set to "0" by the user, the code will use the Galilean-PSATD equations with V=0.
