### ISSUE TITLE
Initial density profile when using more than 4 modes

### ISSUE THREAD

**Issue by syoffe** [fbpic/fbpic#220]
When using FBPIC with Nm > 4, the charge density \rho has a large noise component coming from the mode n = 4. In my test, modes n = 1, 2, 3, 5, 6, ... provided a contribution O(10^{14}) times smaller than n = 0, while n = 4 was the same order as n = 0. Could there be an issue with how charge is deposited onto the grid for that particular mode?

In this particular test, there is a linear plasma ramp starting from z = 0, towards the right of the window:
![n all](https://user-images.githubusercontent.com/678602/37033545-4c90c9f6-213e-11e8-889a-46e2306cca8c.png)
![n 0](https://user-images.githubusercontent.com/678602/37033538-4bb61e0a-213e-11e8-9b8a-8bdee4386894.png)
![n 1](https://user-images.githubusercontent.com/678602/37033539-4bd52cbe-213e-11e8-8bd3-55969d5eb6d1.png)
![n 2](https://user-images.githubusercontent.com/678602/37033540-4bedcc60-213e-11e8-9a79-0a556cff5d31.png)
![n 3](https://user-images.githubusercontent.com/678602/37033541-4c05f196-213e-11e8-909a-61dd1da5eb34.png)
![n 4](https://user-images.githubusercontent.com/678602/37033542-4c1ca936-213e-11e8-96bd-becc4327f466.png)
![n 5](https://user-images.githubusercontent.com/678602/37033543-4c3423ae-213e-11e8-9960-0f8dca18d4af.png)
![n 6](https://user-images.githubusercontent.com/678602/37033544-4c76bdf4-213e-11e8-81f0-481e80572b27.png)

Thanks for your help,
Sam

**Comment by RemiLehe** [comment]
Thanks for reporting this issue!

I think that what you observe is related to the fact that you use `p_nt=4` (4 particles in the azimuthal direction) for the plasma particles. (Could you confirm this?). 

In theory, in order to resolve `Nm` modes correctly, one should use `p_nt = 2*Nm` (it might be that one can get away with less, but that might require some experimentation). I apologize for not including this point in the documentation ; I'll try to do this in the near future. Could you confirm that using p_nt = 14 solves your issue?

The reason for using `p_nt=2*Nm` is because, in FBPIC, when initializing the plasma, the particles are regularly spaced in the azimuthal direction (i.e. they are spaced by an equal angle, which is 2 pi/ p_nt). As consequence, the projection of the particle charge/current on the different modes is similar to a Fourier transform along the theta direction (at least while the particles have not moved much), which would require `2*Nm` points for `Nm` modes.

**Comment by syoffe** [comment]
Thanks a lot, Remi. You are quite right, I was using `p_nt = 4` and increasing this to `p_nt = 14` completely removes the issue. It's interesting that just mode `n = p_nt` suffered. I'll close the issue.

**Comment by RemiLehe** [comment]
Thanks for confirming this, and for closing the issue :)
