### ISSUE TITLE
Periodic boundaries seem broken in dev branch

### ISSUE THREAD

**Issue by Escapado** [fbpic/fbpic#23]
While trying to merge the new higher order shape implementation
into the current dev branch I noticed that errors appear close to the
boundaries in the periodic plasma wave test file:

<img width="1674" alt="screen shot 2016-11-15 at 18 30 58" src="https://cloud.githubusercontent.com/assets/5439360/20316540/8ed8a3d6-ab62-11e6-963a-9eaba0c2a624.png">

Maybe this is related to the "save_periodic" commit ?

**Comment by RemiLehe** [comment]
Thanks for reporting the issue!

I'll have a look. By the way, does this happen also for linear (i.e. order 1) shapes? Does it happen when using the GPU or the CPU?

**Comment by MKirchen** [comment]
It happens with the current dev branch (so linear shape) and we tested only GPU so far.
We had no time anymore today to look further  into this.

**Comment by RemiLehe** [comment]
OK, I just tested it on CPU and the problem did not show up. So it may be related to the GPU stuff. I will try to investigate today.

**Comment by MKirchen** [comment]
@Escapado mentioned to me that this bug is very new, as it did not show up with the previous version of FBPIC that did not yet include the Galilean scheme. I also suspect the "safe_periodic" commit to be the cause of the issue. Maybe exchanging the particles even if there are no guard regions and periodic boundaries might cause problems with the sorting and subsequent GPU deposition?

**Comment by RemiLehe** [comment]
It does seem to be due to the "safe_periodic" commit: I ran the test with the version of the code just before this commit and it did not have the above problem. I also ran the version with the incriminated commit and confirmed that it has the problem.
I'll try to understand why this commit is causing the bug.

**Comment by RemiLehe** [comment]
I think I found the bug. I am preparing a pull request which fixes it.
