### ISSUE TITLE
subsampling

### ISSUE THREAD

**Issue by omriseemann** [fbpic/fbpic#313]
Hi,
I am Omri Seemann, Phd student in Weizmann, I work with Igor Andriyash
I run fbpic for my studies and I have some issues with big data outputs and wish to implement subsampling of the particle data.
I already have written a fork which is ready for pr, (tested and checked for pep8/pyflakes according to readme file)

basically I add a check to apply_selection function for a key "subsampling" which should be an integer.
sampling according to index of particle. using numpy mod function to check if mod(index,subsampling_integer) == 0
Is it ok to issue a pull request?
Thanks.

**Comment by RemiLehe** [comment]
Hi Omri,

Thanks a lot for considering to contribute your subsampling code to FBPIC!

Yes, PR are very much welcome! Feel free to open one, and we'll be happy to review the code.

From your quick description, there is one point that would maybe need to be discussed: because the particles are not stored randomly in memory, using `mod` might introduce unwanted correlations. As a consequence, it could be that the sub-sample of particles that you are creating is not statistically representative of the whole distribution.

For instance, if there are 16 particles per cell, and if the user chooses the subsampling integer to be 32 (=2*16), then all the sampled particles will come from "even" cells (e.g. the 0th cell, the 2nd cell, the 4th cell, etc.). In some cases, this might confuse the user.

For this reason, I think that *randomly* sampling the particles might better, as it does not introduce correlations. (i.e. the user specifies a given subsampling fraction, e.g. `subsampling_fraction = 0.2` ; and then, in `apply_selection`, particles would be selected by doing a random draw, and checking whether the randomly-drawn variable is less than `subsampling_fraction`).

Is it acceptable for you to use "random" subsampling? Would that work for your use case?

**Comment by omriseemann** [comment]
hi,
me and igor thought about this aswell:). we have no objection using
randomization. I didnt do that because I wasnt sure if there are any
complications in using randomization functions  efficiency and in not
having fixed number of particles outputing (probobly isnt fixed in any case
because of boundaries).
ill change it and submit
omri seemann

**Comment by omriseemann** [comment]
yea. actually its not fixed even for any selection criteria 😅

**Comment by omriseemann** [comment]
Yea, sounds good.
