### ISSUE TITLE
Save fields along trajectory

### ISSUE THREAD

**Issue by danielseipt** [fbpic/fbpic#329]
I was trying to add the electric and magnetic fields at the particle positions to the particle diagnostics
using  (self.Ex,self.Ex,... ) of the Particle class.
My essential modification to particle_diag.py reads

>             elif quantity in ["Ex" , "Ey" , "Ez" , "Bx" , "By" , "Bz" ]:
>                 quantity_path = "fields/%s" %(quantity)
>                 self.write_dataset( species_grp, species, quantity_path,
>                         quantity, n_rank, Ntot, select_array )

In principle it works but I encountered some rather strange behavior. 
When tracking a single electron, in every 17th output the fields values are taking odd values. In the case of Ex the values jump to zero at every 17th step, for other field components they take different values.

The following figures show some examples from a laser-wakefield simulation:

![electric_field_bug](https://user-images.githubusercontent.com/39627867/52593207-5f078f80-2e16-11e9-9145-31f9a5ef3e69.png)

![electric_field_bug2](https://user-images.githubusercontent.com/39627867/52593624-65e2d200-2e17-11e9-8500-78b8b4f7cee0.png)

![electric_field_bug3](https://user-images.githubusercontent.com/39627867/52594107-b0188300-2e18-11e9-855e-995fad432557.png)

Is this some bug or am I accessing the particle's gathered fields incorrectly?

Cheers,
Daniel

**Comment by RemiLehe** [comment]
Hi Daniel,

Thanks for your interest in the code, and for reporting this issue!

I think that the reason why you are seeing this is because:

- FBPIC does the particle exchange only every 17 iterations in your case (by "exchange", I mean removing particles that are out-of-bound, resizing the particle arrays, and performing MPI exchanges - when running with multiple MPI ranks ; in FBPIC we do not need to do this operation at every iteration because of the large number of guard cells)
- Whenever particle exchange happens, the position/momenta of the particles are copied into the new, resized array, but the field information is lost (i.e. we reallocate empty fields array):
https://github.com/fbpic/fbpic/blob/dev/fbpic/boundaries/particle_buffer_handling.py#L344
Fundamentally, this is because the fields will be gathered from the grid again before being used to push the particles, so no need to keep the value from the previous time step (except for diagnostics...)

One solution to fix this would be to copy/MPI-communicate the field information from the previous iteration, but that would have a cost in terms of performance. @MKirchen Any suggestion/idea on how to do this differently?

**Comment by danielseipt** [comment]
Thanks Remi for this quick reply.

Another solution I am thinking about right now would be to gather the fields right before
writing them. That way the code runs normally when the fields are not marked for output.
What do you think about this?

**Comment by danielseipt** [comment]
I found another very simple workaround: run the diagnostics after the field gathering in the main PIC loop. That solution works for me in my fork but I'm not sure it would be acceptable for a pull request.

**Comment by RemiLehe** [comment]
Actually, yes, I think this is the best solution!
As far as I can tell I don't see any issue with swapping the diagnostics and the field gather. @MKirchen Do you confirm?

Since you mentioned a pull request, I think that your changes could be very useful for other users as well! So, if you are willing to do so, you can definitely go ahead and open a new PR to the `dev` branch. (See https://github.com/fbpic/fbpic/blob/dev/CONTRIBUTING.md) Thanks!

**Comment by MKirchen** [comment]
Hey,

Yes I think that this is a valid solution which will not infere with anything else. Should we put it after gathering the external fields or before?

Thanks Daniel for looking into this and coming up with a possible solution!

**Comment by RemiLehe** [comment]
Good point: I think that the diagnostics should come after the external fields. Several users pointed out that there is currently no way to see/check the external fields. (e.g. https://github.com/fbpic/fbpic/issues/269)
With the above change, we would be able to see them in the field-on-particle output.

**Comment by danielseipt** [comment]
I did some testing now the order of field gathering and writing the diags interchanged (I put it *after* the external field application). By doing that it might be that the particle id's are assigned in a different way. When I compare the behaviour of the particles with id 0-19 for both cases they clearly show some differences:

![write_gather_20](https://user-images.githubusercontent.com/39627867/52653362-d17f7a80-2ebd-11e9-8f4c-b79be2ca6020.png)

**Comment by RemiLehe** [comment]
Yeah, particles are distributed semi-randomly in the azimuthal direction, so running the code twice will result in different trajectories for a given ID. You could use `np.random.seed` in order to fix this: see [this discussion](https://github.com/fbpic/fbpic/issues/48).

**Comment by danielseipt** [comment]
That worked. After fixing the random seed the ids are the same and the particle orbits are identical. So there seem to be no unwanted side effects by interchanging the diag writing and field gathering.

**Comment by RemiLehe** [comment]
Sounds good, thanks for checking. 
I think that at this point the tests look good, having the field-on-particle output would be a great addition to FBPIC, so if you are interested in opening a pull request, you can definitely go ahead. 
Otherwise, in case you do not have the time, I can certainly also implement it myself based on the above discussion.
Let us know what works best :)

**Comment by RemiLehe** [comment]
Closed by #330
