### ISSUE TITLE
MPI decomposition and KNL performances

### ISSUE THREAD

**Issue by titoiride** [fbpic/fbpic#346]
Dear all developers,
I'm trying to run a FBPIC simulation on the KNL nodes on CINECA. I know you warned that it is not optimized, but right now they are the only type of nodes I have access to.
I'm running on an `Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz` (68 cores).
While running on a single node I noticed that I can boost a bit the simulation by disabling the hyperthreading, but, as soon as I increase the MPI processes, it seems that the simulation slows down.
So, I'd like to better understand how the MPI decomposition is spatially performed (longitudinal domains, right?), to try to increase the performances and try to find the best balance between MPI processes and the number of threads per process.
Is it possible that in the first few iterations of my simulation, which are where I tried to extimate the performances, since the laser is still entering the plasma the MPI domains are unevenly loaded with particles?
Do you have any suggestions on some good processes/threads configuration? I don't mean to scale on a really large number of MPI, I think that 3 or 4 processes can be enough.

Thank you!

**Comment by RemiLehe** [comment]
Thanks for trying out the code :)

Regarding the MPI decomposition: we are planning to add some explanations to the documentation soon. But basically, yes, you are correct that the MPI decomposition is only along z (longitudinal). Because the spectral solver in FBPIC requires a lot of guard cells, creating MPI subdomains comes with a cost, and so we tend to use few MPI ranks, and rely on shared-memory parallelism within each subdomain (in the case of KNL: several threads/cores working together on the same MPI domain). But the best balance between MPI and shared-memory parallelism is not always easy to guess.

For regular CPUs (e.g. Haswell), we typically recommend 1 MPI rank per socket, and then one thread per core within one socket. 

However, for KNL, we did very few tests, in part because the performance is quite bad: see for instance [this post](https://groups.google.com/a/continuum.io/forum/#!searchin/numba-users/KNL%7Csort:date/numba-users/D1wqMGYnzxk/4QTTrzXRBQAJ). If I had to guess, I would maybe recommend 8 MPI ranks and 8 threads per MPI, on a single KNL node, in other words:
```
export NUMBA_NUM_THREADS=8
export MKL_NUM_THREADS=8
mpirun -np 8 python fbpic_script.py
```
And then varying the number of MPI ranks by a factor 2 (and varying the number of threads in an inversely proportional way) to see how it affects the performance.

Does the above help?

**Comment by RemiLehe** [comment]
@titoiride Was the above helpful? Could we close this issue?

**Comment by titoiride** [comment]
Thank you very much for the reply, it was very clear and useful. I will do some test, changing the parameters in the range you suggested. I hope it will speed up the simulation :)

**Comment by RemiLehe** [comment]
@titoiride In case this is useful: note that we recently added documentation on the parallelization and MPI decomposition in FBPIC: https://fbpic.github.io/overview/parallelisation.html.
