### ISSUE TITLE
how to run FBPIC for multi-CPU on Tianhe2 super computing center by a script file

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#357]
Hi all,
I have installed the fbpic program on the Tianhe2 super computing center, but i don't know how to run the simulation by a script file. For example, when i use the EPOCH PIC code on the Tianhe2 super computing center, the script file that run the code is :

`#!/bin/bash
echo Data | yhrun -N 2 -n 48 ./bin/epoch2d
`
where the `epoch2d` is the binary executable file.

In this FBPIC code, can I write the script file as follows?

`#!/bin/bash
export NUMBA_NUM_THREADS=48
export MKL_NUM_THREADS=48
yhrun -N 2 -n 48 python fbpic_script.py`

**Comment by MKirchen** [comment]
Hi,

thanks for your interest in our code!

Please note that FBPIC employs two levels of parallelisation:

1. The first level works only within a single node or socket and will use CPU multi-threading. The first level is the default parallelisation when running FBPIC. In your case, I think each node consists of 24 CPU cores, however these are probably split across 2 sockets per node. In order to run most efficiently, the threading environment variables of FBPIC should be set to `NUMBA_NUM_THREADS=12`  and `MKL_NUM_THREADS=12`. In this case, FBPIC will be parallelized across 12 CPU cores on the first level.

2. The second level allows to use MPI to parallelise the code across multiple nodes (or sockets) by splitting the simulation box in multiple smaller boxes in the longitudinal direction that are computed in parallel. Please note that in this case, you need to set the parameter `n_order` to a finite value, such as 32. When executing FBPIC with multiple MPI processes, the code will automatically parallelize the computation across all of these processes. However, this will only work efficiently for a small number of MPI processes, as the box should not (or cannot) be split in too many small boxes.

In your executing command, I think you request 2 nodes `-N 2` and 48 MPI processes `-n 48`. However, for FBPIC you should only request 4 MPI processes `-n 4` if you want to run on 2 nodes, while each of the 4 MPI processes will make use of the first-level parallelisation on 12 cores.

So if you run this command `#!/bin/bash export NUMBA_NUM_THREADS=12 export MKL_NUM_THREADS=12 yhrun -N 2 -n 4 python fbpic_script.py`, it should launch 4 MPI processes that are distributed across 2 nodes. So on each node, there will be 2 MPI processes running, while each of them will use 12 CPU cores in parallel. So in total 48 CPU cores are used.

Note: For initial testing, I would recommend to only use the first-level parallelisation of FBPIC. You can test if you can successfully run FBPIC on a single node with 24 threads by executing the following command: `#!/bin/bash export NUMBA_NUM_THREADS=24 export MKL_NUM_THREADS=24 yhrun -N 1 -n 1 python fbpic_script.py`

I hope this helps!

**Comment by QJohn2017** [comment]
Hi, @MKirchen 
 Thank you for your help. According to your suggestion, I have changed the `n_order` to 32 in the input script, and changed the job script file to follows:
`#!/bin/bash 
export NUMBA_NUM_THREADS=24 
export MKL_NUM_THREADS=24 
yhrun -N 1 -n 1 python lwfa_script.py`

After that, I submit the job, but something errors occurred:

`
Traceback (most recent call last):
  File "lwfa_script.py", line 20, in <module>
    import numpy as np
  File "/WORK/ac_siom_jsliu_1/qzy/miniconda2/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/WORK/ac_siom_jsliu_1/qzy/miniconda2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/WORK/ac_siom_jsliu_1/qzy/miniconda2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/WORK/ac_siom_jsliu_1/qzy/miniconda2/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/WORK/ac_siom_jsliu_1/qzy/miniconda2/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/WORK/ac_siom_jsliu_1/qzy/miniconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
yhrun: error: cn12030: task 0: Exited with exit code 1

`
Besides, I have another question. The version of my `numba` is 0.26.0, which is lower than 0.43。when I use the command `conda update numba -y`, after some downloading and transition, some errors also occurred:
`
CondaVerificationError: The package for numba located at /WORK/ac_siom_jsliu_1/qzy/miniconda2/pkgs/numba-0.43.1-py27h962f231_0
appears to be corrupted. The path 'lib/python2.7/site-packages/numba/mviewbuf.c'
specified in the package manifest cannot be found.

CondaVerificationError: The package for numba located at /WORK/ac_siom_jsliu_1/qzy/miniconda2/pkgs/numba-0.43.1-py27h962f231_0
appears to be corrupted. The path 'lib/python2.7/site-packages/numba/pycc/modulemixin.c'
specified in the package manifest cannot be found.

CondaVerificationError: The package for numba located at /WORK/ac_siom_jsliu_1/qzy/miniconda2/pkgs/numba-0.43.1-py27h962f231_0
appears to be corrupted. The path 'lib/python2.7/site-packages/numba/runtime/_nrt_python.c'
specified in the package manifest cannot be found.

CondaVerificationError: The package for numba located at /WORK/ac_siom_jsliu_1/qzy/miniconda2/pkgs/numba-0.43.1-py27h962f231_0
appears to be corrupted. The path 'lib/python2.7/site-packages/numba/runtime/_nrt_pythonmod.c'
specified in the package manifest cannot be found.

CondaVerificationError: The package for numba located at /WORK/ac_siom_jsliu_1/qzy/miniconda2/pkgs/numba-0.43.1-py27h962f231_0
appears to be corrupted. The path 'lib/python2.7/site-packages/numba/runtime/nrt.c'
specified in the package manifest cannot be found.
......
`

**Comment by MKirchen** [comment]
Hi, 

these errors are related to problems on your cluster environment / your python package installation.
I cannot help you fixing those. I would suggest you try to install Anaconda from scratch (maybe that helps) and/or ask for support from the supercomputer staff directly.

**Comment by QJohn2017** [comment]
Hi, @MKirchen ,
   Thank you very much ! I have solved the problems above, it is because that the version of my Anaconda is too old. I have installed the latest Anaconda on the computing cluster and the running of the FBPIC code is ok , which displays as follows:
![11](https://user-images.githubusercontent.com/31507149/58156240-3bbb6e80-7ca8-11e9-88f4-f2180477e52c.jpg)

Is it right?

**Comment by MKirchen** [comment]
Looks good! 👍 Now you could try to distribute the simulation across multiple nodes using `-N 2 -n 4` and `NUMBA_NUM_THREADS=12 and MKL_NUM_THREADS=12` and then check if this reduces the simulation time.

**Comment by QJohn2017** [comment]
Hi, @MKirchen ,
  I have a question, when I use 1 node, the script is that
`#!/bin/bash export NUMBA_NUM_THREADS=24 export MKL_NUM_THREADS=24 yhrun -N 1 -n 1 python fbpic_script.py` 

but to your suggestion, when I use 2 nodes, why the script is that:
`#!/bin/bash export NUMBA_NUM_THREADS=12 export MKL_NUM_THREADS=12 yhrun -N 2 -n 4 python fbpic_script.py`
but not the form below ?
`#!/bin/bash export NUMBA_NUM_THREADS=24 export MKL_NUM_THREADS=24 yhrun -N 2 -n 2 python fbpic_script.py` 

and if I want to use `N1` nodes, How should I write the script file ?

**Comment by MKirchen** [comment]
Hey,

I explained this already in my first post (see 1.). Here again in more detail:

In the single node case, I was suggesting 24 threads so that all physical cores of the node are used when running **without** MPI. However, I guess that your hardware layout on a single node consists of 2 sockets with each 12 cores. FBPIC's multi-threading typically runs more efficient if confined to a single socket. So when running **with** MPI, I was suggesting to use 2 MPI processes per node, each of the processes then uses 12 threads on 12 physical cores. This explains the difference in number of threads for both commands.

**Note:** I can be necessary to explicitly force the MPI processes to use a single socket each and to not distribute across sockets. This can typically be done by passing the `--cpu-bind=sockets` to the executing command (i.e. `srun`). So in your case to run on 2 nodes with 4 MPI processes this would be:

`#!/bin/bash export NUMBA_NUM_THREADS=12 export MKL_NUM_THREADS=12 yhrun --cpu-bind=sockets -N 2 -n 4 python fbpic_script.py`

You can also try first to only use 1 node with 2 MPI processes to see how it differs from the initial case without MPI (the one where 24 threads were used):

`#!/bin/bash export NUMBA_NUM_THREADS=12 export MKL_NUM_THREADS=12 yhrun --cpu-bind=sockets -N 1 -n 2 python fbpic_script.py`

**Comment by QJohn2017** [comment]
Hi, @MKirchen ,
  I have tried four cases with different `NUMBA_NUM_THREADS` and `MKL_NUM_THREADS`. and the results as follows:
![11](https://user-images.githubusercontent.com/31507149/58169881-7e8b3f80-7cc4-11e9-96c9-bd3cb205a2a2.jpg)

it can be found that you are right when the nodes is above 1. So, if I want to use 4 nodes, the script can be written as follows?
`#!/bin/bash export NUMBA_NUM_THREADS=12 export MKL_NUM_THREADS=12 yhrun --cpu-bind=sockets -N 4 -n 8 python fbpic_script.py`

is it right? Thank you !

**Comment by MKirchen** [comment]
Yes that is correct. Did you try the `--cpu_bin=sockets` option? Did it work for your supercomputer and did it change the performance?

**Comment by QJohn2017** [comment]
I don't know how to add the `--cpu_bin=sockets` option, does it just add it after the `python fbpic_script.py` in the script file?

**Comment by MKirchen** [comment]
Please look at my previous posts again, I have written it down there.

**Comment by QJohn2017** [comment]
when I use the script `#!/bin/bash export NUMBA_NUM_THREADS=12 export MKL_NUM_THREADS=12 yhrun **--cpu-bind=sockets** -N 1 -n 2 python fbpic_script.py`, some errors occurred:

`yhrun: unrecognized option '--cpu-bind=sockets'
Try "srun --help" for more information
`

**Comment by MKirchen** [comment]
Okay, I am not sure what `yhrun` is doing. I think it is specific to your supercomputer and it looks like it is derived from `srun`, which has the option `--cpu-bind=sockets`. Please ask your supercomputer support how to set this parameter with `yhrun`.

**Comment by QJohn2017** [comment]
Okay, I will ask the administrator to solve this problem. Thank you !

**Comment by QJohn2017** [comment]
@MKirchen ， I asked the administrators for help, the option should be `--cpu_bind=sockets` , but not the `--cpu-bind=sockets`. Then I tried the following two cases and the results are:
![11](https://user-images.githubusercontent.com/31507149/58221986-2cd7c900-7d47-11e9-8332-e13f287bc8f0.jpg)
It can be found that when only 1 node is used, the efficient way to resolve time is the `--cpu_bind=sockets` , but if there 2 or more nodes are used, it is best not include this option

**Comment by MKirchen** [comment]
Okay, good that it works now. You can still try to change parameters and test different things. I think you should be able to get a better performance scaling to multiple nodes. Maybe your administrators can help you improve the performance on this specific supercomputer. I will close this issue now.
