### ISSUE TITLE
some problems about the simulation results by FBPIC

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#366]
Hi, @MKirchen ,
      when I use the input script file the same to that in #362 , the simulation results are full of doubt for me, some iteration results as follows:
![11](https://user-images.githubusercontent.com/31507149/58534003-a4609900-821c-11e9-9543-980d0c0c7ed0.jpg)

1. In the simulation, `every 4000 step iterations represents 200 um length`, it can be seen that, the electron injection occurred at 56000 step iteration, but the injected electrons  stayed in the tail of the bubble in about `3 mm`  length and  attached to the shell electron at the tail of the bubble。the injection occurred in so much long length, I think it is not tally with the facts of LWFA process，is it the FBPIC program itself which lead to this wrong injection?

2. Besides, when I plot the energy distribution of the injected electrons in the end of the simulation, the results are below:
![12](https://user-images.githubusercontent.com/31507149/58534766-b93e2c00-821e-11e9-9992-df6d10bb12bf.jpg)
it can be seen that the energy of the injected electrons are only few MeV, this is not reasonable in LWFA, So, I don't know if it's a reason of this FBPIC code or if it's just the way it is , can you answer it for me ? Thank you !

**Comment by soerenjalas** [comment]
Hi @QJohn2017,
I ran the script you posted in the other issue. To me the phase space looks reasonable. Note that I reduced the range of the colormap. Since the particle density of the beam is lower than that in the plasma wave it does not show up in the 2d histogram otherwise. You can do this under plotting options in the slider widget or with the `vmax` argument when you use the `get_particle` method of the openPMD-viewer. 
![fbpic_issue](https://user-images.githubusercontent.com/10922951/58587077-c8dc6580-825c-11e9-9532-2c5009158e80.png)

In the plot above did you do any selections to the phase space or zoom in on the plot?

**Comment by QJohn2017** [comment]
Okay, When I used the code above to plot the phase space, the results are the same with you , thank you ! Here I have another two questions:
1. In the input script, what does the pulse duration parameter  `ctau ` means ? Is it the FWHM duration or 1/e duration or other means? If it is not the FWHM duration, what is the relationship between them?

2. when I install the openPMD-viewer, I just input the command `pip install openPMD-viewer`, when I use   the openPMD-viewer, sometimes I want to modify the code to plot the figures. So, my question is How can I change the code and put it to use right now?

**Comment by RemiLehe** [comment]
@QJohn2017 `ctau` is defined in the documentation: https://fbpic.github.io/api_reference/lpa_utilities/laser_profiles/gaussian.html

Regarding your initial question on the correctness of simulation results with FBPIC: I agree with @soerenjalas that your simulation results look correct, and that maybe the way in which they were plotted confused you. 
Does @soerenjalas's remarks answer your initial question, and if yes could we close this issue?

**Comment by QJohn2017** [comment]
@RemiLehe , Yes, @soerenjalas really answered my question. Thank you !

**Comment by QJohn2017** [comment]
@RemiLehe ,sorry, the second question above I have not get the answer, which is :
when I install the openPMD-viewer, I just input the command pip install openPMD-viewer, when I use the openPMD-viewer, sometimes I want to modify the code to plot the figures. So, my question is How can I change the code and put it to use right now?

**Comment by RemiLehe** [comment]
Thanks for reminding about this.
However, I am not sure I understood the question.
Could rephrase the question and post it in the [issues of openPMD-viewer](https://github.com/openPMD/openPMD-viewer/issues) (since this is not an issue with `fbpic`)? Also, if you could include a small example of what you are trying to do (e.g. with some code), I think this would help me understand your use case.
