### ISSUE TITLE
fbpic docker

### ISSUE THREAD

**Issue by berceanu** [fbpic/fbpic#378]
I saw there is a [docker container](https://hub.docker.com/r/rlehe/fbpic) for fbpic. Is the corresponding docker file also available, by any chance?

**Comment by RemiLehe** [comment]
Thanks for your interest in this.

The Docker container is a quite outdated though. I was thinking of simply removing it, since the installation of fbpic is usually not complicated (except for linking to the right `mpi4py` on HPC clusters ; but Docker would not help for this), and so running with Docker is usually a complication.

Would you have a specific use case where Docker would be convenient, or is this more out of curiosity?

**Comment by berceanu** [comment]
Thanks for the quick reply. I wanted to update the docker container and use it in a single-GPU configuration (ie, no MPI) to create a demo `fbpic` notebook on [nextjournal](https://nextjournal.com/).

**Comment by RemiLehe** [comment]
OK, cool idea!

In principle, the following ultra-simple Dockerfile should work, at least on CPU
```
FROM continuumio/miniconda

RUN pip install \
	numba \
	scipy \
	h5py \
        mkl \
        cupy-cuda101 \
	fbpic
```
I have tested it for CPU, but not on GPU, as I do not have `nvidia-docker` installed: 
https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)

**Comment by MKirchen** [comment]
@RemiLehe Should we close this?

**Comment by RemiLehe** [comment]
Yes. This could be re-opened if there are more questions on this topic.
