### ISSUE TITLE
Checkpoints with external beams

### ISSUE THREAD

**Issue by soerenjalas** [fbpic/fbpic#39]
This is minor and maybe doesn't even require any changes, but I want to bring it up anyways as I just ran into it.

The example input file only initialises the laser on the first start like:
```python
# Load initial fields
    if use_restart is False:
        # Add a laser to the fields of the simulation
        add_laser( sim, a0, w0, ctau, z0 )
    else:
        # Load the fields and particles from the latest checkpoint file
        restart_from_checkpoint( sim )
```

I needed to use an external electron beam instead of a laser so I just naively replaced `add_laser()` by `add_elec_bunch()`. This is fine for the first start, but leads to problems when restarting from a checkpoint. This is because `restart_from_checkpoint()` only loads particle data that is in `sim.ptcl`, which only contains the plasma particles when jumping into the `else` statement. A workaround is to just reinitialise the particle beam and than have `restart_from_checkpoint()` overwrite the data.
My suggestion would be to maybe have `restart_from_checkpoint()` add a fresh `Particle` object for every species in the checkpoint openPMD file. 
Another way to avoid this confusion could also be to just change the example file to something like

```python
    # Load initial fields
    # Add a laser to the fields of the simulation
    add_laser( sim, a0, w0, ctau, z0 )
    if use_restart is True:
        # Load the fields and particles from the latest checkpoint file
        restart_from_checkpoint( sim )
```
This way the setup is alway the same and `restart_from_checkpoint()` just updates to the current iteration.

**Comment by RemiLehe** [comment]
Hi Soeren,

Sorry for my late reply, and thanks for the feedback.

It is true that it would be nice for `restart_from_checkpoint` to reinitialize a fresh `Particle` object for every species in the checkpoint openPMD file. However, in practice the openPMD file is missing a few information that are needed to initialize a fresh `Particles` in a robust manner. For instance, the openPMD file does not tell whether the particles should be continuously injected or not, and if they should, it does not contain the parameters of the injection (density profile, etc.).
For the case of the electron bunch, it would be fine, as this species is not continuously injected and thus (I think) the openPMD file would contain all the information needed for initialization of a new `Particles` object. However, this would not generalize to other species.

Therefore, for now, I would prefer the solution in which we put `add_laser`/`add_elec_bunch` outside of the `if` block. It is not ideal (e.g. since we are doing extra work to calculate the space-charge field which is then overwritten by `restart_from_checkpoint`), but at least it is robust. 

Does the above make sense, and if yes, would you be willing to do a corresponding pull request?

**Comment by soerenjalas** [comment]
I see the problem. I've created a pull request with the changes I suggested above. Again as this such a minor issue, if you are not happy with the change feel free to reject the PR.
