### ISSUE TITLE
Absorbing/open transverse boundaries 

### ISSUE THREAD

**Issue by JamesCowley** [fbpic/fbpic#399]
Dear Remi,

I noticed a post from February discussing the possibility of open transverse boundaries in FBPIC, similar to the option longitudinally. There are a couple of scenarios that our group is interested in for which this would be very useful (e.g. measuring energy loss of the fields during propagation, I assume with a reflecting boundary this would not be effective). Is this likely to be a feature of the code in a new release in the near future?

Thanks in advance,
James

**Comment by RemiLehe** [comment]
Thanks for the interest in the code!
Yes, the absorbing boundaries is likely to be available within the next few weeks. There is already a pull request in preparation (#370). I has been there for a while, but I should be able to complete it rather soon.

PS: I see that the question is addressed to me directly, but please note that FBPIC is a collaborative effort, and that I am not the only developer :) In particular, @MKirchen co-developped the code from the beginning, and @soerenjalas also added many features.

**Comment by JamesCowley** [comment]
Dear all (!),

That is brilliant news, I look forward to using the new options! Thanks to you and the co-developers for the work you have put into this code, which we are finding very useful. And apologies to the others, for addressing the question to you earlier.

Best regards,
James

**Comment by RemiLehe** [comment]
@JamesCowley Thanks again for you interest in FBPIC.

The absorbing boundaries are now available in the latest release of the code (https://github.com/fbpic/fbpic/releases/tag/0.15.0), which you can download by doing:
```
pip install --upgrade fbpic
```

In order to activate the absorbing boundaries, please pass `boundaries={'z':'open', 'r':'open'}` to the `Simulation` object. Note that activating the absorbing boundaries can make the simulation significantly slower.
