### ISSUE TITLE
Position of lab-diagnostics region in boosted-frame simulations

### ISSUE THREAD

**Issue by OscarJakobssonResearch** [fbpic/fbpic#419]
Dear developers, 

I am new to boosted-frame simulations and somewhat confused about the results I am getting.
For instance, if I run the boosted-frame sample [script](https://github.com/fbpic/fbpic/blob/dev/docs/source/example_input/boosted_frame_script.py) everything works fine. Here 
zmax = 0.e-6-10e-6 
zmin = -30.e-6
and 
z0 = -10.e-6
zfoc = 0.e-6
I can also shift the initial position of the laser by, say, 10 microns by setting
z0 = -10.e-6-10e-6  and zfoc = 0.e-6-10e-6 without seeing anything odd. 
However, if I change the position of the right-hand box edge 
zmax = 0.e-6-10e-6 
zmin = -30.e-6
the lab diagnostics are progressively cut-off from the left-hand side as shown below at the start and end of the simulation:
![Ez_Iteration000000000](https://user-images.githubusercontent.com/55784067/70905595-3040e380-1ffc-11ea-887e-2abf8f3d8c08.png)
![Ez_Iteration000000009](https://user-images.githubusercontent.com/55784067/70906046-5c109900-1ffd-11ea-8373-580703c590cf.png)
In the [documentation](https://fbpic.github.io/advanced/boosted_frame.html#converting-simulation-results-from-the-boosted-frame-to-the-lab-frame) this is attributed to the "...non-simultaneity between Lorentz frames" and "the chosen number of PIC iterations is insufficient". If If I increase Nz, such as to lower dt, and increase the number of PIC iterations I see no change. 
Additionally, if I shift the laser and window forward by 10 microns (+10e-6 instead of -10e-6) the fields are instead initially cut-off at the front but the cut-off region progressively disappears. 

![Ez_Iteration000000001](https://user-images.githubusercontent.com/55784067/70917335-0a740880-2015-11ea-9746-2bfe87c31408.png)

![Ez_Iteration000000009](https://user-images.githubusercontent.com/55784067/70919057-0d242d00-2018-11ea-8d07-4265d400335e.png)

I assume that I am missing something obvious. 

Any help is much appreciated. 

Many thanks, 
Oscar

**Comment by MKirchen** [comment]
Hey Oscar,

Times and positions transform according to these formulas when going to a relativistic frame
with `gamma0`:
    
```
ct' = gamma0*(ct - beta0*z)
z' = gamma0*(z-beta0*ct)
```

By definition, simulations start at `t = t' = 0` both in the lab and in the boosted frame.
In order to define the physics, it is useful to choose the point `t=t'=0, z=z'=0` as a reference because it is the same in both frames. However, as you can see from the equations above, all other positions in the lab frame at `t=0`, correspond to different positions and times in the boosted frame. Moreover, when initializing the physics in the boosted frame at `t' = 0`, negative positions `z' < 0` correspond to information at negative times in the lab frame `t < 0`. 

It is therefore good practice to always set the right edge of the simulation box to `zmax=0` and to define all copropagating properties (e.g. laser or electron beam) at negative positions and with respect to this reference. (In the boosted frame, we can then correctly initialize the laser and electron beam at `t'=0` by knowing their vacuum evolution at negative lab times from analytical formulas). Correspondingly, the interaction region (i.e. the plasma), that shortens by a factor of `gamma0`, should begin at `z=0` and extend to the right.

The time it takes to complete the simulation, in either frame, is then  defined in the input script as the time it takes for the simulation box (moving window) to slide across the interaction region. In the script this time is calculated by:
    
`T_interact = boost.interaction_time( L_interact, (zmax-zmin), v_window )`

Now lets try to explain the issues that you see:
    
1) If you define `zmax < 0` in the input script, the above calculation will result in a too small interaction time. As a consequence, the lab frame diagnostics will miss spatial information  that is only available at later times in the boosted frame, i.e. you will see a cut-off of information at the left side of the diagnostic box for late lab times. 
    
2) If you define `zmax > 0` in the input script, you will miss spatial information that is only available in previous times in the boosted frame, i.e. at `t' < 0`. As the boosted frame simulations only starts at `t'=0`, it is of course not possible to retrieve this information _from the past_.  As a consequence, you will see a cut-off of information at the right side of the diagnostic box for early lab times.

Of course, there would be ways around this problem by correctly defining the physics and diagnostics at the right times and positions and so on. However, the input script is defined such that everything works correctly when using `zmax=0` as the reference position. I would therefore recommend that you just try to follow this approach. This way it is easy to perform  either a lab frame simulation or a boosted frame simulation and get the same physics and correct diagnostic outputs for both cases.

However, I agree that we should explain this aspect in more detail in the documentation.


Additional note:

Apart from the general considerations discussed above, I realised that you also might have to increase the number of iterations `N_step` by `write_period` iterations, i.e. the last command in the input script should then be `sim.step(N_step + write_period)`. This is because the lab output will be buffered and only written to disk every `write_period` iterations. (I admit that we should improve the input script on this matter.)

**Comment by MKirchen** [comment]
Hey @OscarJakobssonResearch,

did my explanation help you? Can I close this issue?

Thanks,
Manuel

**Comment by OscarJakobssonResearch** [comment]
Hi, 

Thank you very much! I appreciate your detailed response. 
My simulations seem to run fine now.

Just a quick question regarding the write_period before I close this issue.
The write_period parameter gives the number of iterations for which the data is accumulated in memory, before written to the disk. So if I am limited by memory I assume that I should use a small write_period to avoid memory error. If this is not the case however, for a short simulation for instance, I could set the write_period to the total number of iterations in the simulation. Is this correct?

With this description I don't see why I would need "to increase the number of iterations N_step by write_period iterations, i.e. the last command in the input script should then be sim.step(N_step + write_period)". I might be misunderstanding the purpose of write_period here. 

Thanks, 
Oscar

**Comment by MKirchen** [comment]
Hey Oscar,

sorry, I missed to answer this!

You are right that you could set `write_period` to the total number of iterations. In that case, it 
is of course sufficient to only run the simulation for `N_step` and not `N_step + write_period`. The reason I wrote that one should use `N_step + write_period` is because typically `N_step >> write_period` where `write_period` would be something on the order `100 - 1000`. To ensure that the last output slices are written to disk, a simple and robust way would just be to run the simulation for `write_period` steps longer than required.  That is why I recommended it here.
