### ISSUE TITLE
Weird results of FBPIC simulation

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#455]
Hi, When I use the fbpic to do the LWFA simulation, the output results is weird that the "positive electrons" were appeared in the bubble:
![捕获3](https://user-images.githubusercontent.com/31507149/84647371-f3679200-af35-11ea-9087-c16b8c4beab0.PNG)

So, I don't know if this weird issue is lead by the FBPIC program or it is the real result?

**Comment by RemiLehe** [comment]
Thanks for reporting this.
This effect is very common in codes that use a quasi-cylindrical representation of fields (i.e. a representation as a **truncated** azimuthal expansion in `theta`, see the [original paper by Lifschitz et al.](https://www.sciencedirect.com/science/article/pii/S0021999108005950)). This includes FBPIC, but also some run modes of WarpX, Osiris, Smilei, etc. 
In these cases, the electrons of course always have a negative charge ; however, the **deposited charge density** may appear to have positive areas (as you showed). This happens because of the truncation in azimuthal modes ; if a large number of modes were used, you would not observe this.
In general, this happens when the electron beam breaks the assumption of nearly-cylindrical symmetry. (Remember that quasi-cylindrical codes like FBPIC assume that all the simulated structures are close to cylindrically symmetry.) This is clearly the case for the electron beam in the above example, as the beam has a strong transverse oscillation.
In this case, a rigorous simulation should either use more azimuthal modes (which may be impractical due to the computational costs) or use a 3D Cartesian code.

**Comment by QJohn2017** [comment]
Dear @RemiLehe , thank you for your advice, When I increase the `Nm`, the wired result above disappeared. Thank you agian, and this issue can be closed now !
