### ISSUE TITLE
Difference in field and particle diagnostics of plasma particles

### ISSUE THREAD

**Issue by pkmanwani** [fbpic/fbpic#469]
was running a pwfa simulation on FBPIC with Nm=2 and had a question on the diagnostics. I was using the field diagnostic 'rho_plasma_electrons' to get the plasma density and the results were similar to the simulations I ran in QuickPIC. I wanted to check the phase space of the plasma electrons and used the particle diagnostics for it but I wasnt able to interpret the results as the particle diagnostics showed non-zero values at places which were zero in 'rho_plasma_electrons'. 

I am attaching the plots here.

![image](https://user-images.githubusercontent.com/21289171/88953606-03b99f00-d24e-11ea-8b3f-486c1df56720.png)

![image](https://user-images.githubusercontent.com/21289171/88953582-fb616400-d24d-11ea-8388-4ea974edda85.png)

This might be a cause of the different weightage given to the particles owing to the cylindrical mesh. What would be the correct way to interpret the results and what units are the particle numbers in?

**Comment by RemiLehe** [comment]
Thanks for the question, and sorry for the late reply.

I think that the differences between the plot of `rho` and the particle histogram are here probably because:
- the plot of `rho` corresponds to a **slice** (here at y=0)
- the particle histogram corresponds to a **projection**. In other words particles that are far from the axis, but happen to have x=0 (but large y), will contribute to the histogram, appear near x=0 in the plot. This is probably why you are seeing some unexpected non-zero density near x=0.

In order to obtain a **slice** with the particle histogram, you can try to explicitly select the particle along y, so as to only retain a thin slice:
<img width="782" alt="Screen Shot 2020-08-02 at 9 40 22 PM" src="https://user-images.githubusercontent.com/6685781/89146507-c7fe2e00-d508-11ea-8139-c925fb7a2f19.png">

Regarding the numbers on the colorbar: these number correspond to the absolute number of physical particle accumulated into each bin of the histogram (summed along the direction of projection). It is therefore not straightforward to relate this to the density (e.g. one needs to extract the size of the bins of the histogram in order to do so).

**Comment by pkmanwani** [comment]
Hi @RemiLehe, thanks for answering my question. It clears up the confusion I had. 
I have a follow-up question. When extracting the macroparticle number from the bins, is the weight information needed or is it automatically handled by openpmd?

**Comment by RemiLehe** [comment]
Hi,
The histogram from `openPMD-viewer` automatically takes into account the weight information, so that the quantity that is plotted is the number of **physical particle**, not the number of **macroparticles**.
Does this answer your question?

**Comment by pkmanwani** [comment]
Okay, that makes sense. Thank you @RemiLehe for answering all these questions. It certainly helps!
