### ISSUE TITLE
Boosted Frame Shape error

### ISSUE THREAD

**Issue by andrefantoine** [fbpic/fbpic#471]
Hi, 
I am running boosted frame simulations on FBPIC v0.17.1, and continue to run into an error involving a shape  mismatch in the back transformed diagnostic, I ran it once and had no issues, but running it again I the following errors.

Also my simulation box is defined as follows:

#The simulation box
Nz = 600         # Number of gridpoints along z
zmax = 0.e-6     # Length of the box along z (meters)
zmin = -100.e-6
Nr = 75          # Number of gridpoints along r
rmax = 150.e-6   # Length of the box along r (meters)
Nm = 2           # Number of modes used

when it fails I receive this:
----------------------
Restoring modules from user's fbpic

TENSORFLOW USERS:
You must use the python3.6-anaconda/5.2.0 module to run TensorFlow.
See https://arc-ts.umich.edu/greatlakes/software/tensorflow for more
information.

OMP: Info #274: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

NumbaWarning: /home/aantoine/.conda/envs/fbpic/lib/python3.8/site-packages/numba/np/ufunc/parallel.py:355:
The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 10006. The TBB threading layer is disabled.

FBPIC (0.17.1)

Running on GPU 

Calculating initial space charge field...
Done.

Initializing laser pulse on the mesh...
Done.

Traceback (most recent call last):
  File "ZEUS_chirp_test.py", line 215, in <module>
    BackTransformedParticleDiagnostic( zmin, zmax, v_window,
  File "/home/aantoine/.conda/envs/fbpic/lib/python3.8/site-packages/fbpic/openpmd_diag/boosted_particle_diag.py", line 117, in __init__
    self.create_file_empty_slice(
  File "/home/aantoine/.conda/envs/fbpic/lib/python3.8/site-packages/fbpic/openpmd_diag/boosted_particle_diag.py", line 358, in create_file_empty_slice
    dset = species_grp.require_dataset(
  File "/home/aantoine/.conda/envs/fbpic/lib/python3.8/site-packages/h5py/_hl/group.py", line 198, in require_dataset
    raise TypeError("Shapes do not match (existing %s vs new %s)" % (dset.shape, shape))
TypeError: Shapes do not match (existing (1440,) vs new (0,))
--------------------------------------------------------------------

**Comment by MKirchen** [comment]
Hey,

please make sure that the output directory is empty before running the simulation.

Let me know if this solved the issue.

Cheers,
Manuel

**Comment by andrefantoine** [comment]
This did indeed solve the issue, this is an interesting issue, I can only guess that this has something to do with the code trying to overwrite the old files?

**Comment by MKirchen** [comment]
Hey,

sorry for the confusion. This is not really an issue but expected behavior:

When running in the boosted frame, particle data is appended continuously to the output files. This is because information at a given single point in time in the lab frame is generated at multiple times in the boosted frame - a consequence of the Lorentz transform. Hence, we cannot know a priori how many particles are written to a file and therefore have to resize it on-the-fly. 

As a consequence, when restarting the simulation, the shapes of the new and existing files will not match.

We could prevent this error by automatically deleting all files in the output directory at the beginning of a simulation. However, we deliberately chose not to, to prevent accidentally deleting important files.

Cheers,
Manuel

(Note: We should maybe improve this and at least print a meaningful warning.)
