### ISSUE TITLE
Question: Can we use CUDA compilation option for unified memory?

### ISSUE THREAD

**Issue by kookjine** [fbpic/fbpic#476]
Hello all,

While I was using CUDA option in FBPIC, many times my simulations have stopped because of the lack of CUDA memory.
As the title says, can FBPIC use unified memory?
Or is FBPIC already using it?

Thanks!

**Comment by RemiLehe** [comment]
Thanks for the question @kookjine !

FBPIC does not support unified memory. In fact, using unified memory would not be a very good solution to the lack of GPU memory, because in this case, even though the code would be able to run without crashing, it would become extremely slow once the simulation exceeds the GPU memory. (This is because the code would spend a lot of time swapping memory between the GPU and CPU in this case.)

If you have the possibility to do so, I would recommend to run the simulation across several GPUs (with MPI), so that you can use the combined memory of these GPUs to avoid running out of GPU memory.

**Comment by kookjine** [comment]
I imagined it could slow down the simulation, but wasn't sure.
Actually I have used MPI for GPUs in FBPIC. 
(The FBPIC document is very detailed and friendly, thanks a lot.)
But even with 16 GPUs (12 GB*16), it couldn't manage the simulation size.. lol

Thanks for replying Remi!
