### ISSUE TITLE
range of values for `ParticleChargeDensityDiagnostic`

### ISSUE THREAD

**Issue by berceanu** [fbpic/fbpic#496]
1. Why does `rho_electrons` contain positive values? According to the [docs](https://fbpic.github.io/api_reference/diagnostics.html#fbpic.openpmd_diag.ParticleChargeDensityDiagnostic), it is the 

> charge density of the specified species

i.e. the density of the plasma electrons in this case.

2. Looking at the `HDF5` file, it is measured in C/m^3, so shouldn't I get 1 if I divide it by `(-q_e * n_e)`? Instead, I get `rho_electrons.min() / (-q_e * n_e) = 0.08681711041436878`

Relevant code bits:

```python
n_e=8.0e18 * 1.0e6,  # Density (electrons.meters^-3)
p_rmax=25.0e-6
[...]
plasma_elec = sim.add_new_species(
    q=-q_e,
    m=m_e,
    n=n_e,
    dens_func=dens_func,
    p_zmin=p_zmin,
    p_zmax=p_zmax,
    p_rmax=p_rmax,
    p_nz=p_nz,
    p_nr=p_nr,
    p_nt=p_nt,
    )
plasma_ions = sim.add_new_species(
    q=q_e,
    m=m_p,
    n=n_e,
    dens_func=dens_func,
    p_zmin=p_zmin,
    p_zmax=p_zmax,
    p_rmax=p_rmax,
    p_nz=p_nz,
    p_nr=p_nr,
    p_nt=p_nt,
)
[...]
sim.diags = [
    [...]
    ParticleChargeDensityDiagnostic(
        period=diag_period,
        sim=sim,
        species={"electrons": plasma_elec},
    ),
]
```

```python
rho_electrons, info = ts.get_field(
    field="rho_electrons",
    iteration=382,
    plot=True,
)
```

![rho_electrons](https://user-images.githubusercontent.com/4405658/100393959-1dc08e00-3044-11eb-95ad-876d3a6547d9.png)

**Comment by berceanu** [comment]
I see the same issue in the [LWFA + ionization example](https://fbpic.github.io/example_input/ionization_script.html).

![rho_electrons](https://user-images.githubusercontent.com/4405658/100482145-1b6f3a00-30ff-11eb-98f3-56a566eb574e.png)

**Comment by RemiLehe** [comment]
Thanks for reporting this issue.

Regarding 1. (positive value): this is in fact somewhat expected. The reason is that the charge density that is written to the file is **smoothed** by default (so that it looks a bit less noisy). Because of the specific way in which it is smoothed (spectral filter in the Fourier-Bessel space), this can result to slightly positive value, especially near sharp gradients. (e.g. in your case, the positive values seem to appear near the sharp radial edges of the plasma)

Regarding 2. (values that do not match the expected physical values): this is unexpected. Are you maybe running boosted-frame simulation in this case? Would you be willing to share an input script that reproduces this issue?

**Comment by berceanu** [comment]
> Regarding 2. (values that do not match the expected physical values): this is unexpected. Are you maybe running boosted-frame simulation in this case? Would you be willing to share an input script that reproduces this issue?

Well, I suppose the [ionization example script](https://github.com/fbpic/fbpic/blob/c31f73c656756f2b540975a3828cf64f8ff30792/docs/source/example_input/ionization_script.py) would do.

The density of `elec` electrons (species `"electrons"`) is `n_e = 7.e24`.

```python
rho, rho_info = ts.get_field(
    field="rho_electrons",
    iteration=1750,
    plot=True,
)
print(rho.min())  # -13835750.875595493
# shouldn't this be ~1?
print(rho.min() / (-q_e * n_e))  # 12.336566479068079
```
