### ISSUE TITLE
particle per cell

### ISSUE THREAD

**Issue by dmargarone** [fbpic/fbpic#554]
Hi guys !!

Hope you all are doing great. 

Please, could anyone suggest, based on their experience, what is the optimum value one must used for p_nz, p_nr and p_nt.

Thanks.

**Comment by dmargarone** [comment]
Hi guys,
I guess I partially find the answer for my question. p_nz and p_nr may be ok but the constraint for p_nt is number of modes. I am closing the issue, but if anyone find a more correct solution please do share .....

Thanks
DM

**Comment by MKirchen** [comment]
Hey DM,

Sorry for the late answer.

I would recommend the following settings for typical LWFA/PWFA cases:

- In the radial direction, use `p_nr >= 2`. Usually `p_nr = 2` is good.
- In the longitudinal direction, use `p_nz >= 1`. Often `p_nz = 1` is sufficient unless you have a low longitudinal grid resolution (e.g. with some PWFA cases) or if you want to resolve small longitudinal features in the plasma density profile (e.g. with shock-front injection). Also, it can be necessary to increase p_nz (and sometimes the longitudinal grid resolution) when running in the boosted frame, because features in the longitudinal density profile are contracted in the boosted frame.
- In the azimuthal direction, use at least `p_nt = 2*Nm` (see also Issue #220). Note that some cases might require more particles in theta.

Hope that helps,
Manuel

**Comment by dmargarone** [comment]
Hi Manuel,

Thank you so much for your reply. I was not well in the last couple of weeks, thats why responding late. 

I have one more question. How do I know how many particles per cell (PPC). For example, if I use:

p_nz = 2
p_nr = 2, 
p_nt = 4

How many PPC are there ?

Thank you.
DM
