### ISSUE TITLE
"positive" electrons of self-injection and bubble shell in boost frame?

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#557]
Hi, When I do LWFA simulations by using a boost frame, there are always "positive" electrons that appeared in bubble and bubble shells no matter I use two modes (Nm=2) and three modes (Nm=3).  Should I use 4 or more modes? But with the increase of modes, more and more time is consumed. So, is there any other way to eliminate or suppress these "positive"  electrons? Thank you !
![image](https://user-images.githubusercontent.com/31507149/133188863-3721a5d1-f705-411b-8155-7b2dd45b8cf0.png)

**Comment by MKirchen** [comment]
Hey,

yes, you can try to use more modes (up to 4 or 5). While this might help to help to better resolve the injected asymmetric beam distribution, it could also be that the injection process itself is not accurately modelled due to some other issue.
Please remember that correctly modelling self-injection can be challenging, especially in the boosted frame.
I advice you to have a look again at the earlier issues where we already discussed this: #455 and #503.

Thanks,
Manuel

**Comment by QJohn2017** [comment]
Hey, @MKirchen, Thank you very much. In these days, I tried to increase the modes to 4, but got the same results as above. You said that the "positive" electrons may come from the the back-transformation of the data from the boosted frame to the laboratory frame, is this meant that the charge density in boosted frame (e.g. the hdf5 files in `daigs` files) should be normal ? But I plotted the bubble density in this file there are  still "positive" electrons coming up. So, Is there any reference or article showed that the positive charge density come from the back-transformation of the data from the boosted frame to the laboratory frame?

**Comment by MKirchen** [comment]
Hey,

Based on your observation that the non-backtransformed output (`diags`) also shows regions of "positive" electrons, I conclude that the first part of my initial answer was incorrect for your specific case. The issue likely shows up because the azimuthal distribution of the charge density that forms the bubble is not entirely captured by 4 or less modes. However, without knowing more details about the simulation setup, it is difficult to further asses the problem.
