### ISSUE TITLE
Unexpected initial oscillation for electron bunch added with add_particle_bunch_from_arrays() in boosted frame

### ISSUE THREAD

**Issue by YongMa1988** [fbpic/fbpic#558]
Hi,

I tried to simulate external injection in boosted frame with add_particle_bunch_from_arrays() function, the beam has Gaussian distributions in all 6 dimensions, i.e., (x, y, z, ux, uy, uz) using the following settings:

```
bunch_sigma_x = 0.5e-6
bunch_sigma_y = 0.5e-6
bunch_sigma_z = 1.0e-6
bunch_sigma_ux = 0.1
bunch_sigma_uy = 0.1
bunch_sigma_uz = 20.
bunch_uz_max   = 200.

bunch = add_particle_bunch_from_arrays( sim,-e,m_e, bunch_x, bunch_y, bunch_z, bunch_ux, bunch_uy, bunch_uz, bunch_w, direction='forward', z_injection_plane=None, boost=boost, initialize_self_field=False )
```

The electron beam was Initialized behind the peak of the laser pulse with a certain delay where the laser field is not completely zero. So, at t = 0, there is an oscillation with the spacing of the laser wavelength in real space. Does that means the electron beam has already interacted with the laser pulse before the start of the simulation? I tried it with  initialize_self_field=False and True, but seeing the same results. I have attached a plot of the electron beam and the laser pulse at t0.

Does anyone know how to initialize a particle bunch probably?

Thanks a lot!
Yong

<img width="589" alt="Screen Shot 2021-09-14 at 11 02 31 PM" src="https://user-images.githubusercontent.com/34725295/133364124-5381ed55-ba25-4ccf-8ff2-e6b8c0b4e71c.png">

**Comment by RemiLehe** [comment]
Thanks for raising this point.

I will answer assuming that the above figure is from the "back-transformed" diagnostics (i.e. the diagnostics that reconstruct the lab-frame data from a boosted-frame simulation).

In that case: yes, the bunch actually already interacted with the laser before being captured by the first back-transformed diagnostic (i.e. the one for `t_lab = 0`).

This is because, in a boosted-frame simulation, the simulation starts at `t_boost = 0`, not `t_lab = 0`. Due the Lorentz transform between the time in the boosted frame (`t_boost`) and the time in the lab frame (`t_lab`), the bunch is actually initialized in a way that corresponds to `t_lab < 0`:
```
t_lab = gamma_boost * ( t_boost + beta_boost * z_{bunch, boost) )
```
(with `z_{bunch,boost} < 0` at the beginning of the simulation: see the regular diagnostics from this simulation, instead of the back-transformed ).
As a consequence, the bunch has some to propagate and interact with the laser between the time when it is initialized and the time when it is captured by the first back-transformed diagnostic.

If you want to avoid this issue, you can "freeze" the bunch until it reaches a given position (e.g. `z = -55 um` in your simulation). This can be done by calling `add_particle_bunch_from_arrays` with `z_injection_plane = -55e-6`.

Does this answer your question?

**Comment by YongMa1988** [comment]
Hi Remi,

Thanks a lot for the explanation! 
And thanks for the suggestion-that's exactly what I wanted I think!

Best, 
Yong
