### ISSUE TITLE
GPU's unequal memory usage 

### ISSUE THREAD

**Issue by TomPaolo** [fbpic/fbpic#586]
Dear developers, 
I noticed that by using multiple GPU's the memory usage can be quite different among the single GPU's, so that the optimization of the numerics can be less straightforward. This happened when I used a 16xV100 system and a new 2xA100 80GB one.   For the last case, I saw even a 4:1 ratio of the allocated memories.  The  MPI  command for the last case is the standard mpirun -np 2 script_name.py . 
Am I missing something important in the multiple GPU's usage?  
Many thanks in advance
Paolo

**Comment by RemiLehe** [comment]
Thanks for raising this issue @TomPaolo, and sorry for the late reply.

Just to be sure I understand the issue, could you confirm that this is the test that you did:
- Run the script on **16** V100 GPUs with `mpirun -np 16 script_name.py`
- Run the **same** on **2** A100 GPUs with `mpirun -np 2 script_name.py`

If that it correct, I would indeed expect each of the 2 A100 to have a lot more allocated memory then each of the 16 GPUs, just because the same problem is divided across fewer GPUs. (See [this page](https://fbpic.github.io/overview/parallelisation.html) for more details on how we decompose the simulation across GPUs.)

Did I correctly understand the problem, or did you instead actually also run on only **2** V100 GPUs (not 16) when making the above observation?

**Comment by TomPaolo** [comment]
Hi Remi, no sorry I wasn't clear. 
I run some simulations on 16xV100 and I found that sometimes the memory is not equally divided among each GPU. Now I'm running on 2xA100 and I found that sometimes this happens, too. This is not happening any time, though. The main limitation I found is that the numerics cannot be optimized so as to roughly fill the memory of each GPU. I'm running with the command 

nohup mpirun -np 2 python script_name.py  > out.log & with the 2xA100

I'm attaching the nvidia-smi output for one of the unequal memory distribution cases.

Thanks a lot
Paolo

![SMI-unequal](https://user-images.githubusercontent.com/75040201/167792582-305f82d6-7f40-41e4-9c14-0b1c37f2b667.png)

**Comment by ncpathak** [comment]
Dear All,

Sorry for interrupting, but I also meet with the same problem when I tried to use more than one GPU. I used 2 GPUs (each with 40 GB memory: 2xA100).  After some time the simulation was terminated with an error message: "GPU reached out of memory on MPI rank 0 (Error occurred in fbpic function 'add_buffers_gpu')".

I hope this may give you some clear idea what might be going wrong in our case(s).

Thank you.

**Comment by RemiLehe** [comment]
OK, thanks for reporting this @TomPaolo @ncpathak and for clarifying the issue.

In principle, the uneven use of memory could be due to a few reasons. 

But the first that comes to mind is that, for simulations with a moving window, the plasma progressively fills the simulation box (as the moving window progressively moves into the plasma). In this case, since different GPUs take care of different parts of the simulation domain, one GPU might have a lot of plasma particles while another might have very few particles. This should however even out later in the simulation, as the moving window starts being entirely in the plasma region.

@TomPaolo Does that match the case that you are currently looking at?

**Comment by TomPaolo** [comment]
Hi @RemiLehe and @ncpathak, thanks for the commitment. I do usually use up/down ramps of scale-lengths exceeding hundreds of microns, so it's unlike that half window (in the case of the 2xA100 run) will get more than four times the particles of the other. Another possibility is the accumulation of trapped particles in a bucket, but I think it's a remote one. I'll do some test on both the sides once the GPU's will be free and I'll report the outcomes. Is it possible to accommodate the longitudinal decomposition of the window so as to avoid not equally distributed memory insurgence? Thank you that much. Paolo

**Comment by ncpathak** [comment]
Dear All, 
In my case, the problem disappears after using 4 GPUs (4xA100). Now, the code is running consistently, and even with restartable files. 
Also, in my previous attempt with 2 GPUs, the problem of 'out of memory' appear after  ~ 5 ps (1.5 mm propagation length in plasma). At the moment, I have no idea what happened to the memory allocation. Increasing the number of GPUs is the only quick solution for me. (Maybe I should read more about how multiple GPU works).

Thank you.

**Comment by RemiLehe** [comment]
@TomPaolo Sorry for the late reply, and thanks for adding these details.
Regarding the density up-scale: note that the plasma is initialized with a fixed number of particles per cell, irrespective of the density. (The density upramp modifies the "weight" of those macroparticles - i.e. how many physical particles they represent - but not the actual number of macroparticles.) So it is in principle possible that even the low-density rising edge of the up-ramp could cause significant load-imbalance across the GPUs.

Adjusting the domain decomposition in `z` is not currently supported, and it is unlikely to be added in the near future.

**Comment by RemiLehe** [comment]
@ncpathak Thanks for sending this info.
Yes, it could be that your simulation is simply too big for the (limited) memory of your 2 GPUs. In this case, the only practical solution is to use more GPUs (as you did), or to use GPUs models that have more memory per GPU (e.g. there is a 80 GB version of the A100). In general, it is true that GPUs have much lower amount of memory than CPUs, and so it is much more likely to reach out-of-memory on GPUs, for large simulations.

**Comment by RemiLehe** [comment]
I will close this issue for now, but @TomPaolo feel free to add more details if you do more tests in the future.
