### ISSUE TITLE
Colliding pulse injection

### ISSUE THREAD

**Issue by HaoPengYY** [fbpic/fbpic#589]
Dear all,

Hi. Thanks for the wonderful code. I would like to do a simulation in which the electrons are injected by a laser counterpropagating with the driving laser. It seems not possible to initialize such an inject laser using the `add_laser_pulse` method, use the `ExternalField` class seems an option, but it loses the details of the laser propagating in the wakefield. Do you have any suggestions?

**Comment by MKirchen** [comment]
Hi @HaoPengYY,

Thanks for your question. Please note that you can also ask such kind of questions in our Slack channel (https://slack-fbpic.herokuapp.com/) where other users can sometimes help you a bit quicker.

Both options, `add_laser_pulse` and `ExternalField` are possible when using a moving window in the simulation. In the former case, you have to inject the laser from a moving antenna that is located at right edge of the simulation box and moves with it (by choosing `method = 'antenna'` and specifying `v_antenna` and `z0_antenna`). You also have to explicitly specify the propagation direction of the colliding laser profile (`propagation_direction=-1`).

However, when using a moving window you initialize the counter-propagating laser within the plasma. This might lead to numerical errors as the plasma particles will see an abrupt increase of the laser field at the right edge of the simulation box. Nevertheless, this problem is probably not too much of an issue if the normalized peak vector potential is small (`'a0 <<1'`) at the point of initialization.

An alternative solution is to use a very long simulation box which contains the entire plasma (if it is reasonably short). In this case you would not use a moving window and just emit the colliding laser pulse from a non-moving antenna at the right edge of the simulation box (in the vacuum region just behind the end of the plasma). 

The optimal solution depends on the exact use case that you consider.

I hope that helps,
Manuel

**Comment by HaoPengYY** [comment]
@MKirchen Thanks a lot for your reply. Yes, simulating counterpropagating lasers is always a pain. The last solution you proposed should be a solution, but it should take a lot of time.
