### ISSUE TITLE
Laser apparently is not being properly absorbed in rmax after long propagation distances

### ISSUE THREAD

**Issue by abonatto** [fbpic/fbpic#603]
Dear Developers,

We are running some long simulations (1000+ um) for a LWFA operating in the self-modulated regime, in a Gaussian plasma-density profile. Initially, the laser envelope (which is longer than the plasma wavelength) gets focused and modulated, as expected. However, once it reaches rmax after defocusing, it seems to get cumulated in the radial boundary, rather than being absorbed. This behavior gets quite intense as the simulation keeps running, producing non-physical behavior in the plasma electrons. We are using open boundaries for both r and z and, in order to try to solve the issue, we repeated the same simulation with the following values for n_damp:

- r:32, z: 64
- r:64, z: 64
- r:128, z: 128

However, as you can see in the PDF attached, despite the "residual" laser amplitude being greatly reduced, the issue is still quite appreciable. Do you have any suggestion (preferentially other than increasing rmax) on how to address this issue?

Kind Regards,

Alexandre Bonatto
[laser_snapshots.pdf](https://github.com/fbpic/fbpic/files/9251400/laser_snapshots.pdf)

**Comment by RemiLehe** [comment]
Thanks for reporting this issue.

Yes, it seems that the open boundaries have some numerical issues, as reported also here:
https://github.com/fbpic/fbpic/issues/534
We haven't had time to look at this problem in detail. For now, it seems that the best work-around is to leave some vacuum space between the plasma and the radial boundary (as discussed also https://github.com/fbpic/fbpic/issues/534), i.e. to initialize the plasma only up to a certain radius `p_rmax` so that `p_rmax < rmax` (where `rmax ` is the radius of the simulation box).

Does that work in your case?

**Comment by abonatto** [comment]
Hi Remi,

Thanks for your fast reply, and for pointing out the discussion #534. Yes, I believe this should work. We will add a radial down-ramp and a vacuum region, and then repeat the simulation. Once I have new results, I will post them here.

**Comment by abonatto** [comment]
Hi Remi,

For the record, after some testing we managed to mitigate the aforementioned effect by increasing rmax from 20um to 100um, with a 5um-long down-ramp followed by 75um of vacuum. There are still some residual "laser reflection" but, since the time for each simulation already increased from ~15h to ~33h, we will keep this rmax.
