### ISSUE TITLE
Recording the particles that leave the box and are removed

### ISSUE THREAD

**Issue by buffnerd11** [fbpic/fbpic#605]
What is the best way to record the momenta and weight (etc.) of the particles that pass through the axial boundaries and are removed from the simulation?

**Comment by RemiLehe** [comment]
Thanks for your interest in the code and for your question.

Unfortunately, there isn't a very convenient/clean way to do this in FBPIC.

One way to achieve this would be to dump all the particles that are e.g. in the very first cell and very last cell (in `z`) at **each** iteration. (You can use the `select` argument [here](https://fbpic.github.io/api_reference/diagnostics.html#particle-diagnostic.) Additionally, you could also add a condition to only dump particles that have a velocity that points towards the exit (so as to avoid dumping any entering particles.

For efficiency, you may also want to actually do this only every 10-20 iterations (and in this case, dump all the particles in the first and last 10-20 cells), instead of doing this at every single iteration.

Does this make sense?

**Comment by buffnerd11** [comment]
Thanks for taking some attention to my question! 

That is a plausible solution. I believe that if I dump the particles in the first and last cell, then in order to see which particles actually leave, in my post-processing analysis I will need to:
1) push the dumped p with the dumped gathered E&B,
2) push the dumped x with the modified p
3) and then check to see whether or not x will have crossed the boundary

I wanted to make sure I wasn't overlooking a clean/convenient way to count these particles. Thanks for your help.

**Comment by RemiLehe** [comment]
Sounds good.
The above post-processing steps make sense.
You can also use the particles' unique ID (activated with the FBPIC `track` method) to verify that the post-processing indeed counted each exiting macroparticle only once.

**Comment by buffnerd11** [comment]
In order to this post-processing method with a moving window, it would be nice if my "select" boundaries in my ParticleDiagnostic would move along with the boundaries of the simulation. Is there a way to have a "select" rule that changes from iteration to iteration?
