### ISSUE TITLE
Resolution and on-axis phenomenon of long wavelength CO2 laser for low plasma density

### ISSUE THREAD

**Issue by ycaophysics** [fbpic/fbpic#613]
Hi. I'm doing some simulations with 9200nm CO2 laser and low plasma density in range of 10^15~10^17. However, I'm not sure about the resolution requirement for such long wavelength. (Usually I used 40/wavelength longitudinally and 4/wavelength transversely for 800nm laser injection)  
When I used some simulation parameters used by some papers other people have published (simulated with a different code), it shows some weird density behavior on the axis. (I don't really know if that's physical or not. It seems like self injection but as I checked they are not accelerated). They used very low resolution (20 cells per wavelength longitudinally, and 10 cells per wavelength transversely) which may not be suitable for FBPIC, and they see no self injection. I'm not really sure if it's the problem of FBPIC or the problem of their code. 

Here is the paper I was trying to model: [Evolution of the self-injection process in long wavelength infrared laser driven LWFA ](https://doi.org/10.1063/5.0027167)  The image I'm trying to produce is FIG 10(a). 

So here are some images I produced with their low resolution parameters:
![image](https://user-images.githubusercontent.com/70364621/186989850-1807b05c-bc49-4c88-8915-13eda29e0332.png)
Here is an image of using much better resolutions:
![image](https://user-images.githubusercontent.com/70364621/186990210-91159743-4c38-4b0c-9cfc-5de3118754a5.png)

Here are the files I've used to produce those images:
[CO2_highresol_Kumar.py.txt](https://github.com/fbpic/fbpic/files/9436436/CO2_highresol_Kumar.py.txt)
[CO2_lowresol_Kumar.py.txt](https://github.com/fbpic/fbpic/files/9436435/CO2_lowresol_Kumar.py.txt)

**Comment by RemiLehe** [comment]
Thanks for your interest in the code and sorry for the late reply.

When you mention the problem on axis: could you confirm that what you mean is that the electron density is very "noisy" close to the axis?

If yes, then this is indeed an issue that is often observed with PIC codes that use a cylindrical grid (like FBPIC), as opposed to PIC codes that use a Cartesian grid (as in the above paper). You can somewhat mitigate this issue by using more particles per cell (I would recommend e.g. `p_nz = 2` instead of `p_nz = 1`) and by using a wider shape factor (i.e. passing `particle_shape='cubic'` in the FBPIC `Simulation` object).

Regarding the resolution of the simulation: the resolution that you are currently using seems reasonable to me.

Feel free to let me know if you have additional questions.
