### ISSUE TITLE
settings of laser focus position and beam focus position

### ISSUE THREAD

**Issue by pistachio-xin** [fbpic/fbpic#623]
I wanted to simulate the external injection process by fbpic, using the function ' add_particle_bunch_gaussian'.  In most time I simulated, the energy of beam will decrease wherever the phase of beam is.  I found that the parameter zf will influence the gained energy of beam. So I wonder that how to set a resonable value of 'zf'(beam focus positin) in  ' add_particle_bunch_gaussian' and 'zf'(laser focus position). Maybe it is a physics problem, so if everyone know how to understand those two parameters,  I will thanks very much.

**Comment by RemiLehe** [comment]
Hey, sorry for the late reply.
In general, `zf` and `tf` should be set together, so that the beam is in an accelerating phase of the wakefield.
Are you able to plot the `Ez` field in the simulation, and the position of the particles with respect to this? This might give you some hints as to why the beam is not accelerating and how to correct it.
