### ISSUE TITLE
Highly uneven memory usage distribution in a parallel 2-GPU job

### ISSUE THREAD

**Issue by abonatto** [fbpic/fbpic#632]
Dear Developers,

I am running a parallel job using two A6000 GPUs, each with 48 GB of memory. During the simulation, one GPU maintains approximately constant memory usage (~10 GB) while the other GPU's usage grows linearly, eventually reaching 48 GB and causing the job to crash. Can you confirm if this uneven memory distribution between the GPUs is expected? I am not familiar with how parallelization is internally handled by CUDA, cupy, and/or FBPIC. My assumption is that the simulation domain is evenly distributed between the GPUs, resulting in more similar memory usage on each GPU.

I am using FBPIC 0.21, cupy 10.5.0, Nvidia drivers 470.161.03, and CUDA Version: 11.4

Please see here a plot of the memory usage (per GPU and total),
[GPUS.pdf](https://github.com/fbpic/fbpic/files/10488588/GPUS.pdf)

and see below the error messages:
```
  File ".../file.py", line 191, in <module>
    sim.step(N_step)
  File "/home/.../anaconda3/envs/fbpic/lib/python3.10/site-packages/fbpic/main.py", line 455, in step
    self.comm.exchange_particles(species, fld, self.time)
  File "/home/.../anaconda3/envs/fbpic/lib/python3.10/site-packages/fbpic/boundaries/boundary_communicator.py", line 748, in exchange_particles
    self.exchange_particles_aperiodic_subdomain( species, fld, time )
  File "/home/.../anaconda3/envs/fbpic/lib/python3.10/site-packages/fbpic/boundaries/boundary_communicator.py", line 825, in exchange_particles_aperiodic_subdomain
    add_buffers_to_particles( species, float_recv_left, float_recv_right,
  File "/home/.../anaconda3/envs/fbpic/lib/python3.10/site-packages/fbpic/boundaries/particle_buffer_handling.py", line 356, in add_buffers_to_particles
    species.Ez = cupy.empty( shape, dtype=np.float64 )
  File "/home/.../anaconda3/envs/fbpic/lib/python3.10/site-packages/cupy/_creation/basic.py", line 22, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/_core/core.pyx", line 171, in cupy._core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 698, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1375, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1396, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1076, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1097, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1335, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 1,130,688,000 bytes (allocated so far: 45,889,959,424 bytes).
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node gff exited on signal 9 (Killed).
--------------------------------------------------------------------------
```
Kind Regards,
Alexandre Bonatto

**Comment by RemiLehe** [comment]
Hi @abonatto,

Thanks a lot for reporting this! 
My guess is that what you are observing is actually expected. 
As you were guessing, the domain is evenly divided, along the `z` direction, across MPI ranks, as represented here:
https://fbpic.github.io/overview/parallelisation.html
Now the memory that each GPU needs to allocated can be broadly divided into two categories:
- Memory to store the fields on a grid: this does not change during the simulation, since the size of the grid is fixed. This is probably the 10 GB that you are seeing.
- Memory to store the particles: this can change during the simulation, since particles can be added into the simulation box (especially with a moving window), and on the other hand particles can be removed as they exit the domain.

In your case, I am guessing that your simulation runs with a moving window. This means that the simulation box is almost empty of particles at `t=0`, but will then be progressively filled with particles as the window moves into the plasma. Because of the longitudinal domain decomposition, the GPUs do not fill up at the same time. At first, the GPU that has the sub-domain at the right-hand side of the simulation box will be progressively filled with particles (if the moving window moves to the right), while the other GPU will still be empty of particles. I think that this is why only one of your GPUs is going out of memory in the above case (i.e. it's subdomain is still being filled by the plasma, as the moving window is moving).

Does the above make sense? In the end, I think that the solution would essentially be to use more GPUs, so that the plasma can fit in memory.

**Comment by abonatto** [comment]
Hi @RemiLehe,

Thank you very much for the details on the memory categories, and for the clear explanation of what might be happening. Indeed, I am using a moving window, and your explanation makes perfect sense!
