### ISSUE TITLE
different figures for Bx on separate systems

### ISSUE THREAD

**Issue by rezaplasma** [fbpic/fbpic#659]
Hi
I run example of FBPIC script (lwfa_script) on local computer and computational server so that I got different figures for `Bx` in first iteration

on server:
![Bz(s)](https://github.com/fbpic/fbpic/assets/98335092/7586176a-af32-4624-b022-6b5211cbcd12)
![Bz_z(s)](https://github.com/fbpic/fbpic/assets/98335092/e2dbc1c2-ba85-459c-b4b8-a5ae9ff690db)
on local computer:
![Bx](https://github.com/fbpic/fbpic/assets/98335092/0b11e2ee-e69d-4445-811e-1d3d7a218f31)
![Bx_z](https://github.com/fbpic/fbpic/assets/98335092/0c46a8e9-b363-496f-824b-34f7207ecff0)

what's the problem?
thanks

**Comment by hightower8083** [comment]
@rezaplasma the problem is definitely with the computational server case. 
To debug this, one would need to know how FBPIC was installed on the server, and check if there were no warnings, errors  in the output of this simulation.\
Judging by the  ranges of you z-axis, the `zmin` and `zmax` values  are different for these cases, (-10,30) and  (-30,30) , and the problematic simulation has a longer box. Are there any other differences between these cases?

**Comment by rezaplasma** [comment]
Hi @hightower8083 

thanks for your reply and sorry for my late reply
yes, they are different cases chosen for two simulations but they do not affect the problem

I have installed FBPIC with `conda `package  and then run `pip install fbpic` statement as mentioned in document of installation!
should I use another way to install fbpic on computational server?
and does this problem generally affect the final results of simulation?

Thanks
